### ISSUE TITLE
Not an issue, but a radar suggestion

### ISSUE THREAD

**Issue by William-Rea** [atticuscornett/AtmosWeather#1]
I love the app so far, but would it be possible to make the radar a bit taller? I'm viewing on a 16:10 aspect ratio, and it's a bit cramped. Thank you!

**Comment by atticuscornett** [comment]
Thanks for the suggestion! I'll test out some larger sizes, which should hopefully be in the next release.

**Comment by atticuscornett** [comment]
The latest commit (https://github.com/atticuscornett/AtmosWeather/commit/0a463b108fded78f4387e371227cb36964d46822) should fix this. You can take a look at the update on the web version. (https://atticuscornett.github.io/AtmosWeather/platforms/browser/www/index.html)
Let me know if that fixes the issue!

**Comment by William-Rea** [comment]
It's much better! Thank you!
