### ISSUE TITLE
proprietary component slipped in: GMS

### ISSUE THREAD

**Issue by IzzySoft** [atticuscornett/AtmosWeather#15]
My scanner just reported to me that somehow GMS has slipped into your app, so I have to mark it with the `NonFreeComp` ant-feature for now. Can you please check what dragged it in and, hopefully, get rid of it again?

Hm, [looks like it might be intentional](https://github.com/atticuscornett/AtmosWeather/blob/main/android/app/build.gradle#L54) even:

```gradle
try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch(Exception e) {
    logger.info("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}
```

May I suggest you [an alternative push service](https://gitlab.com/-/snippets/1896503#push) which is entirely FOSS? It meanwhile even offers a FOSS implementation of FCM which you could use as fallback in case no other distributor was found on the device. I use @UnifiedPush for quite a while via the NTFY distributor, works excellent. One can freely choose a [Push Client/Manager](https://android.izzysoft.de/applists/category/named/network_push) and even self-host its server.

**Comment by atticuscornett** [comment]
Whoops, I don't use any push notification services and I haven't changed any of the background location code - the addition of GMS was probably due to the migration to Capacitor and Capacitor plugins. Capacitor should be compatible with all Cordova plugins, so I will see if switching to the Cordova geolocation plugin solves the issue. My apologies for not catching that!

**Comment by atticuscornett** [comment]
Hmmm... I don't send push notifications so I assume that is part of Capacitor's default build config. I will look into it. My apologies for letting that slip through!

**Comment by atticuscornett** [comment]
I just checked - it seems that is the default build configuration for CapacitorJS. (I assume to make it easy to implement push notifications.) I have no `google-services.json`, so in theory (assuming I understand the code correctly), there should be no GMS library in the built APK. Still, to be extra sure, I have removed those lines from the build file and checked that Atmos Weather still builds properly. I will double-check that everything works soon and push out an update soon to be totally sure that the library is removed.

**Comment by IzzySoft** [comment]
You can use `apktool d <apk-file>` to create the smali structures and then dive into the smali dirs to see if there are any references left. You can of course also use my library scanner, which automates that, see [Identify modules in apps](https://android.izzysoft.de/articles/named/app-modules-2) for details.

**Comment by atticuscornett** [comment]
Looked through the smali dirs with apktool and didn't notice any references to `com.google.gms.google-services`.
Tried to use your automated scanner as well, but noticed a few errors pop up when I ran it. (Seemed to be trying to run Linux commands, but I use Windows. Or perhaps I set it up incorrectly.) Still need to double-check that the new build works, but I will probably put out an update in the next few days.

**Comment by IzzySoft** [comment]
> Seemed to be trying to run Linux commands

I use it on Linux indeed. Need to check if it runs explicit Linux commands (probably the wrapper for `apktool` is the culprit here)… OK, there we go:

```php
$apktool = '/web/ftp/repo/fdroid/lib/radar/tool/apktool';
$libdir  = '/web/ftp/repo/fdroid/lib';
```

These are the paths you'd need to adjust. They are Linux/Unix paths (using forward slashes). I see in the script I use those as well, I could replace them with `PATH_SEPARATOR` to let PHP choose the correct one. But then it uses `find` (which IMHO is not available on Windows by default in a GNU compatible variant (and I won't integrate PowerShell, sorry), though there are [GNU-Tools packages providing it](https://gnuwin32.sourceforge.net/packages/findutils.htm)) and `rm` (which I could move to a function with OS-specific calls, or make it "PHP native" (there is no recursive deletion, I had to walk the tree then myself). OTOH, it should run fine in Cygwin (e.g. using Mobaxterm or the likes).

If you'd be OK using the `findutils` package and want to test it, I could attempt a "rewrite" as outlined.

**Comment by atticuscornett** [comment]
Actually, no worries - I got the scanner working on my Raspberry Pi (and emulating Linux on Windows should be easy enough for others with WSL.) Strangely, it indicates that GMS is still in the APK. I missed something it seems. I will look into this further.

**Comment by atticuscornett** [comment]
Ah, I caught the culprit. It seems to be `@capacitor/geolocation` that has another reference buried deep in it somewhere. CapacitorJS supports Cordova plugins, so it should hopefully be as simple as swapping that plugin back to the Cordova plugin.

**Comment by atticuscornett** [comment]
I swapped Capacitor's geolocation plugin for Cordova's plugin, and the scanner now says that no offending libraries have been found. I also tested it on Android and the app still functions as expected. The fix has been released as Atmos Weather v2.0.1 (https://github.com/atticuscornett/AtmosWeather/releases/tag/v2.0.1).

**Comment by IzzySoft** [comment]
Interesting. The Flutter plugin by the same name (geolocation) had the very same issue (see [here in my snippet](https://gitlab.com/-/snippets/1896503#flutter-and-geolocation), and also in the comments below it). Might give you some clues even if Flutter ≠ Capacitor.

**Comment by IzzySoft** [comment]
Confirmed, AF removed (effective with the next sync). Thanks!
