### ISSUE TITLE
Function over Form, Please

### ISSUE THREAD

**Issue by sanctimoniousape** [atticuscornett/AtmosWeather#24]
Your forced intro with ridiculously slow transitions, SLOW animations everywhere, and no options in settings to eliminate this time-wasting fluff made me immediately uninstall this app.  The functions look very useful, but I can't deal with the misplaced priorities.  Maybe I'll try it again later after you've had a chance to rectify this usability issue, should you care to do so. 

Thanks for reading my rant.

**Comment by atticuscornett** [comment]
Sorry you had a bad experience with Atmos Weather. Admittedly, the slow transitions are a holdover from when the app was originally made. This app was first made for a competition and so I had very limited time to work on optimization - the animation was slow to mask loading times. (Yes, this was sloppy, I know, but it was a quick workaround to meet the competition deadline.) Since then, the app has become much more optimized, but the animations have lingered. I will look into shortening the animations and perhaps even allowing them to be disabled entirely.

**Comment by smith901** [comment]
I 2nd this motion. Haven't uninstalled because it is kinda useful. Haven't used it as much as I should considering rain means I don't make money. And its been an abnormal amount of rain here lately.

**Comment by smith901** [comment]
I 2nd this motion. Haven't uninstalled because it is kinda useful. Haven't used it as much as I should considering rain means I don't make money. And its been an abnormal amount of rain here lately.

**Comment by atticuscornett** [comment]
I have just released Atmos Weather v2.1.2-beta.1 as a pre-release. This version adds settings to customize the tab transition duration and the app launch logo animation. By default, the tab transition is slightly shorter than in earlier versions, but it can be disabled entirely by setting the transition duration to 0ms. The Atmos Weather logo animation is now disabled by default (although you may see it briefly while the app is still loading).

You can download the new pre-release here: https://github.com/atticuscornett/AtmosWeather/releases/tag/v2.1.2-beta.1

I have a few unrelated bugs to fix before releasing the final version of v2.1.2, so it may take a little longer for the feature to be officially released. Let me know what you think of the changes!

**Comment by atticuscornett** [comment]
Atmos Weather v2.1.2 has been released! This version includes settings for changing page transition speed and disabling the app logo intro. It also includes other small quality-of-life features and bug fixes. As previously mentioned, the transition animations are shorter by default, but you can disable them entirely in settings.

You can download the new release here: https://github.com/atticuscornett/AtmosWeather/releases/tag/v2.1.2

This update should fix all the issues you mentioned - but if I missed something, re-open this issue and let me know!
